"$schema" = 'https://starship.rs/config-schema.json'

format = """
(fg:color_orange)\
$os\
$username\
(fg:color_orange)\
$directory\
(fg:color_yellow)\
$git_branch\
(fg:color_aqua)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
(fg:color_blue)\
$docker_context\
$conda\
(fg:color_bg3)\
$time\
$line_break
$character
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
format = '[ $user ]($style)'
disabled = false

[directory]
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = "| "
format = '[[ $symbol $branch](fg:color_fg0)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_fg0)]($style)'

[nodejs]
symbol = "| "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[c]
symbol = "|  "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[rust]
symbol = "| "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[golang]
symbol = "| "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[php]
symbol = "| "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[java]
symbol = "|  "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[kotlin]
symbol = "| "
format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[haskell]
symbol = "| "

format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[python]
symbol = "| "

format = '[[ $symbol( $version)](fg:color_fg0)]($style)'

[docker_context]
symbol = "| "
format = '[[ $symbol( $context)](fg:#83a598)]($style)'
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[conda]
format = '[[ $symbol( $environment) ](fg:#83a598)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[ |  $time](fg:color_fg0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[➜](bold fg:color_green)'
error_symbol = '[➜](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
